"""
Artifact generation: render terraform.tfvars for each selected env
from the validated lld_json, and upload to OBS.
"""
from __future__ import annotations

import json
from typing import TYPE_CHECKING, Any

import structlog
from jinja2 import Environment as JinjaEnv, StrictUndefined

from agent.models.domain_map import DOMAIN_MODULE_MAP, domains_to_envs
from agent.utils.obs_state import save_artifact

if TYPE_CHECKING:
    from agent.models.run_state import RunState
    from agent.orchestrator import StepContext

log = structlog.get_logger()


def _b(val: Any) -> str:
    """Render a boolean/string value as Terraform HCL literal."""
    if val is True or str(val).lower() in ("true", "yes"):
        return "true"
    if val is False or str(val).lower() in ("false", "no"):
        return "false"
    return str(val)


def _s(val: Any) -> str:
    """Render a string value quoted for HCL."""
    if val is None:
        return '""'
    return f'"{val}"'


def _list_of_str(val: Any) -> str:
    """Render a comma-separated string or list as HCL list literal."""
    if val is None:
        return "[]"
    if isinstance(val, list):
        items = val
    else:
        items = [v.strip() for v in str(val).split(",") if v.strip()]
    return "[" + ", ".join(f'"{i}"' for i in items) + "]"


_ENV_TEMPLATES: dict[str, str] = {
    "01-foundation": """\
# Generated by LZ Agent — run {{ run_id }}
# Domain: D1 (Org & Accounts) + D2 (Identity)
home_region = {{ s(d1.home_region or "cn-east-3") }}

master_account_id = {{ s(meta.get("master_account_id", "")) }}

# Org structure
org_name                   = {{ s(d1.org_name) }}
log_archive_account_name   = {{ s(d1.log_archive_account_name or "lz-log-archive") }}
log_archive_account_email  = {{ s(d1.log_archive_account_email) }}
audit_account_name         = {{ s(d1.audit_account_name or "lz-audit") }}
audit_account_email        = {{ s(d1.audit_account_email) }}
enable_identity_center     = {{ b(d1.enable_identity_center) }}
identity_center_admin_email = {{ s(d1.identity_center_admin_email) }}
rgc_log_retention_days     = {{ d1.rgc_log_retention_days or 365 }}

# OUs
enable_workloads_ou     = {{ b(d1.enable_workloads_ou) }}
workloads_ou_name       = {{ s(d1.workloads_ou_name or "Workloads") }}
enable_sandbox_ou       = {{ b(d1.enable_sandbox_ou) }}
sandbox_ou_name         = {{ s(d1.sandbox_ou_name or "Sandbox") }}
enable_infrastructure_ou = {{ b(d1.enable_infrastructure_ou) }}
infrastructure_ou_name  = {{ s(d1.infrastructure_ou_name or "Infrastructure") }}

# Satellite accounts
security_ops_account_name   = {{ s(d1.security_ops_account_name or "lz-security-ops") }}
security_ops_account_email  = {{ s(d1.security_ops_account_email or "") }}
network_ops_account_name    = {{ s(d1.network_ops_account_name or "lz-network-ops") }}
network_ops_account_email   = {{ s(d1.network_ops_account_email or "") }}
ops_monitoring_account_name = {{ s(d1.ops_monitoring_account_name or "lz-ops-monitoring") }}
ops_monitoring_account_email = {{ s(d1.ops_monitoring_account_email or "") }}

# Identity Center / IAM baseline (D2)
enable_scim_sync            = {{ b(d2.enable_scim_sync) }}
session_duration_admin      = {{ s(d2.session_duration_admin or "PT4H") }}
session_duration_developer  = {{ s(d2.session_duration_developer or "PT8H") }}
platform_team_group_name    = {{ s(d2.platform_team_group_name or "lz-platform-admins") }}
password_min_length         = {{ d2.password_min_length or 12 }}
password_max_age_days       = {{ d2.password_max_age_days or 90 }}
password_reuse_prevention   = {{ d2.password_reuse_prevention or 5 }}
mfa_enforce_console         = {{ b(d2.mfa_enforce_console) }}
root_disable_console        = {{ b(d2.root_disable_console) }}
require_uppercase           = {{ b(d2.require_uppercase) }}
require_numbers             = {{ b(d2.require_numbers) }}
require_special_chars       = {{ b(d2.require_special_chars) }}
""",

    "02-network": """\
# Generated by LZ Agent — run {{ run_id }}
# Domain: D3 (Network)
home_region = {{ s(d1.home_region or "cn-east-3") }}

er_instance_name            = {{ s(d3.er_instance_name or "lz-hub-er") }}
er_asn                      = {{ d3.er_asn or 64512 }}
er_availability_zones       = {{ list_s(d3.er_availability_zones) }}
enable_default_propagation  = {{ b(d3.enable_default_propagation) }}

enable_cloud_firewall        = {{ b(d3.enable_cloud_firewall) }}
cfw_name                     = {{ s(d3.cfw_name or "lz-hub-cfw") }}
cfw_log_retention_days       = {{ d3.cfw_log_retention_days or 7 }}

enable_nat_gateway           = {{ b(d3.enable_nat_gateway) }}
nat_gateway_name             = {{ s(d3.nat_gateway_name or "lz-hub-nat") }}
nat_gateway_spec             = {{ s(d3.nat_gateway_spec or "Small") }}
shared_bandwidth_size_mbps   = {{ d3.shared_bandwidth_size_mbps or 100 }}

enable_vpn                   = {{ b(d3.enable_vpn) }}
enable_direct_connect        = {{ b(d3.enable_direct_connect) }}

sandbox_vpc_name             = {{ s(d3.sandbox_vpc_name or "lz-sandbox-vpc") }}
sandbox_vpc_cidr             = {{ s(d3.sandbox_vpc_cidr) }}
sandbox_subnet_cidr          = {{ s(d3.sandbox_subnet_cidr) }}
sandbox_availability_zone    = {{ s(d3.sandbox_availability_zone) }}
enable_vpc_flow_logs         = {{ b(d3.enable_vpc_flow_logs) }}

enable_waf                   = {{ b(d3.enable_waf) }}
waf_instance_count           = {{ d3.waf_instance_count or 2 }}
enable_private_dns           = {{ b(d3.enable_private_dns) }}
""",

    "03-security-audit": """\
# Generated by LZ Agent — run {{ run_id }}
# Domains: D4 (Sharing) + D5 (Security) + D6 (Audit)
home_region = {{ s(d1.home_region or "cn-east-3") }}

# D4 — Shared Resources
kms_key_alias                  = {{ s(d4.kms_key_alias or "lz-master-key") }}
kms_key_rotation_enabled       = {{ b(d4.kms_key_rotation_enabled) }}
kms_key_rotation_interval_days = {{ d4.kms_key_rotation_interval_days or 365 }}
enable_shared_obs              = {{ b(d4.enable_shared_obs) }}
shared_obs_bucket_name         = {{ s(d4.shared_obs_bucket_name or "") }}
enable_sfs_turbo               = {{ b(d4.enable_sfs_turbo) }}
share_resources_to_account_ids = {{ list_s(d4.share_resources_to_account_ids) }}

# D5 — Security Center
enable_secmaster        = {{ b(d5.enable_secmaster) }}
secmaster_workspace_name = {{ s(d5.secmaster_workspace_name or "lz-security-workspace") }}
enable_hss              = {{ b(d5.enable_hss) }}
hss_quota_count         = {{ d5.hss_quota_count or 10 }}
hss_version             = {{ s(d5.hss_version or "hss.version.enterprise") }}
enable_dbss             = {{ b(d5.enable_dbss) }}
enable_dsc              = {{ b(d5.enable_dsc) }}

# D6 — Audit & Logging
cts_tracker_name           = {{ s(d6.cts_tracker_name or "lz-org-cts-tracker") }}
cts_log_retention_days     = {{ d6.cts_log_retention_days or 90 }}
cts_enable_notifications   = {{ b(d6.cts_enable_notifications) }}
enable_lts                 = {{ b(d6.enable_lts) }}
lts_retention_days         = {{ d6.lts_retention_days or 30 }}
obs_lifecycle_cold_days    = {{ d6.obs_lifecycle_cold_days or 30 }}
obs_lifecycle_expiry_days  = {{ d6.obs_lifecycle_expiry_days or 365 }}
enable_config              = {{ b(d6.enable_config) }}
enable_org_aggregator      = {{ b(d6.enable_org_aggregator) }}
""",

    "04-ops-finance": """\
# Generated by LZ Agent — run {{ run_id }}
# Domains: D7 (Ops) + D8 (Finance)
home_region = {{ s(d1.home_region or "cn-east-3") }}

# D7 — Ops & Monitoring
enable_cloud_eye         = {{ b(d7.enable_cloud_eye) }}
alarm_notification_email = {{ s(d7.alarm_notification_email) }}
cloud_eye_alarm_level    = {{ d7.cloud_eye_alarm_level or 2 }}
enable_aom               = {{ b(d7.enable_aom) }}
aom_workspace_name       = {{ s(d7.aom_workspace_name or "lz-ops-workspace") }}
enable_smn_topics        = {{ b(d7.enable_smn_topics) }}
smn_topic_name_ops       = {{ s(d7.smn_topic_name_ops or "lz-ops-alerts") }}
enable_functiongraph     = {{ b(d7.enable_functiongraph) }}

# D8 — Finance Governance
required_tags              = {{ list_s(d8.required_tags or "ManagedBy,Environment,CostCenter") }}
enforce_tag_policy         = {{ b(d8.enforce_tag_policy) }}
budget_alert_email         = {{ s(d8.budget_alert_email) }}
monthly_budget_usd         = {{ d8.monthly_budget_usd or 0 }}
budget_alert_threshold_pct = {{ d8.budget_alert_threshold_pct or 80 }}
""",

    "05-perimeter": """\
# Generated by LZ Agent — run {{ run_id }}
# Domain: D9 (Data Perimeter)
# IMPORTANT: enforce_mode defaults false — verify VPC endpoints before enabling
home_region = {{ s(d1.home_region or "cn-east-3") }}

allowed_regions              = {{ list_s(d9.allowed_regions) }}
enable_region_scp            = {{ b(d9.enable_region_scp) }}
enable_root_protect_scp      = {{ b(d9.enable_root_protect_scp) }}
enable_require_mfa_scp       = {{ b(d9.enable_require_mfa_scp) }}
enable_deny_internet_gw_scp  = {{ b(d9.enable_deny_internet_gw_scp) }}
scp_enforcement_mode         = {{ b(d9.scp_enforcement_mode) }}
enable_obs_vpcep             = {{ b(d9.enable_obs_vpcep) }}
enable_iam_vpcep             = {{ b(d9.enable_iam_vpcep) }}
enable_dns_vpcep             = {{ b(d9.enable_dns_vpcep) }}
obs_require_vpcep_only       = {{ b(d9.obs_require_vpcep_only) }}
""",
}


def _render_tfvars(env: str, run_id: str, lld_json: dict) -> str:
    template_str = _ENV_TEMPLATES.get(env, "")
    if not template_str:
        return f"# No template for env {env}\n"

    jinja = JinjaEnv(undefined=StrictUndefined)
    jinja.globals.update(b=_b, s=_s, list_s=_list_of_str)

    ctx = {
        "run_id": run_id,
        "meta": lld_json.get("_metadata", {}),
        "d1": lld_json.get("D1", {}),
        "d2": lld_json.get("D2", {}),
        "d3": lld_json.get("D3", {}),
        "d4": lld_json.get("D4", {}),
        "d5": lld_json.get("D5", {}),
        "d6": lld_json.get("D6", {}),
        "d7": lld_json.get("D7", {}),
        "d8": lld_json.get("D8", {}),
        "d9": lld_json.get("D9", {}),
    }
    return jinja.from_string(template_str).render(**ctx)


async def execute(state: "RunState", ctx: "StepContext") -> None:
    prefix = f"agent-runs/{state.run_id}/artifacts"
    state.artifacts_obs_prefix = prefix
    log.info("step08_artifacts_start", envs=state.deploy_envs)

    for env in state.deploy_envs:
        tfvars = _render_tfvars(env, state.run_id, state.lld_json)
        key = save_artifact(state.run_id, f"{env}/terraform.tfvars", tfvars)
        log.info("tfvars_generated", env=env, obs_key=key)

    # Also save the validated LLD as YAML for the approval email attachment reference
    import yaml as _yaml
    lld_out = {k: v for k, v in state.lld_json.items() if k in state.deploy_domains or k == "_metadata"}
    lld_yaml = _yaml.dump(lld_out, allow_unicode=True)
    save_artifact(state.run_id, "lld-validated.yaml", lld_yaml)
    log.info("lld_yaml_saved")
